// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fard/core/models/download_entry.dart';
import 'package:fard/features/prayer_tracking/data/daily_record_entity.dart';
import 'package:fard/features/quran/data/datasources/local/entities/ayah_entity.dart';
import 'package:fard/features/quran/data/datasources/local/entities/bookmark_entity.dart';
import 'package:fard/features/quran/data/datasources/local/entities/surah_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AyahEntityAdapter());
    registerAdapter(BookmarkEntityAdapter());
    registerAdapter(DailyRecordEntityAdapter());
    registerAdapter(DownloadEntryAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(SurahEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AyahEntityAdapter());
    registerAdapter(BookmarkEntityAdapter());
    registerAdapter(DailyRecordEntityAdapter());
    registerAdapter(DownloadEntryAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(SurahEntityAdapter());
  }
}
